### ISSUE TITLE
m] (default mapping) stops working when buffer text changes

### ISSUE THREAD

**Issue by levouh** [chentau/marks.nvim#10]
Open a buffer with marks, remove a few lines, issue the default command for `m]` and note that it goes to the wrong line (where the mark used to be)

The builtin "goto mark" with a backtick still goes to the correct location (where the current sign is)

**Comment by chentau** [comment]
Yep, I’m aware of this issue. Will be working on a fix asap since this bug is pretty annoying.

**Comment by levouh** [comment]
I didn't even get an email until you just merged this now, sorry I didn't see it earlier to help with testing.

Will let you know, thanks for the quick turnaround!

**Comment by levouh** [comment]
Works perfectly for me now.
