### ISSUE TITLE
MarksToggleSigns is unreliable

### ISSUE THREAD

**Issue by mystilleef** [chentau/marks.nvim#39]
Since the last update, `MarksToggleSigns` does not work reliably. It doesn't hide all marks in the buffer anymore. Also, `set_next` doesn't work reliably anymore. I've attached a video of  the issue.

### Video

https://user-images.githubusercontent.com/273399/140695597-dfa393f5-db91-480f-80a1-c93c4ff74135.mp4

### Config

```lua
    -- marks
    use({
      "chentau/marks.nvim",
      config = function()
        require("marks").setup({
          default_mappings = false,
          force_write_shada = false,
          refresh_interval = 1250,
          builtin_marks = { ".", "<", ">", "^", "[", "]", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", [[']], [["]], },
          mappings = {
            next = "m]",
            prev = "m[",
            set_next = "m,",
            delete_line = "m<bs>",
            delete_buf = "m<space>",
          },
          excluded_filetypes = {
            "NeogitCommitMessage",
            "NeogitCommitPopup",
            "NeogitPopup",
            "NeogitStatus",
            "TelescopePrompt",
            "help",
            "packer",
          },
        })

```

### Neovim version

```
NVIM v0.6.0-dev+560-g1fdbd29df
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by chentau** [comment]
I can’t seem to be able to view your attached gif. Can you provide a concrete repro?

**Comment by mystilleef** [comment]
> I can’t seem to be able to view your attached gif. Can you provide a concrete repro?

I think this was a configuration issue on my part. After reinstallation, I can't reproduce the issue.
