### ISSUE TITLE
`set_next` doesn't work when `builtin_marks` are enabled

### ISSUE THREAD

**Issue by mystilleef** [chentau/marks.nvim#41]
When `builtin_marks` are set, `set_next` doesn't work. Works fine when `builtin_marks` are empty. 

I use `Neovim HEAD`.

**Comment by chentau** [comment]
Moving to builtin marks is disabled, since there is a bad interaction with moving to and then setting the ‘ mark at the same time. However, it should be possible to allow movement to the other builtin marks. I can take a look when I have time.

**Comment by mystilleef** [comment]
> 

Perhaps, I don't understand. I'm trying to set new marks using `set_next`, not move to marks. When `builtin_marks` are enabled, that `API` doesn't work.

**Comment by chentau** [comment]
Whoops, I misread that as `get_next`. It should be a simple fix.
