### ISSUE TITLE
`builtin_marks` 0 to 9 are not shown

### ISSUE THREAD

**Issue by mystilleef** [chentau/marks.nvim#44]
Maybe I'm doing something wrong, but I notice marks `0` to `9` are not shown even when I add them to the `builtin_marks` list. Could they be added to the list?

**Comment by chentau** [comment]
Numbered marks are a bit special, since they cannot be set, only jumped to. I suppose I could enable signs for number marks, but is there a particular reason you want them to be visible?

**Comment by mystilleef** [comment]
The same reason I want the other builtin marks visible, so I can jump to them. 😀 On a serious note, they're a quick way to jump to relevant changes made in the document. The previous marks plugin I used made them visible and I found them useful. At the moment, I use Telescope's marks picker to jump to them.
