### ISSUE TITLE
What if you added jump to mark?

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [chentau/marks.nvim#46]
What if you added jump to mark? is it is possible?

**Comment by ahmed-rezk-dev** [comment]
What if you added jump to mark? is it is possible?

**Comment by chentau** [comment]
Do you mean jumping to named marks? If so, then vim has this feature built in; see vim help for ‘

**Comment by ahmed-rezk-dev** [comment]
That's what I mean. You are right. 
Thank you!
