### ISSUE TITLE
LSP highlighting stops working

### ISSUE THREAD

**Issue by fimkap** [chentau/marks.nvim#59]
It's a nice plugin, but when the plugin is activated, LSP highlighting of a symbol under cursor stops working.

**Comment by chentau** [comment]
my initial uninformed guess is that this is caused by a bad interaction between a cursorhold autocmd and this plugin - see #40 for more discussion.

**Comment by fimkap** [comment]
Thank you. A workaround with `refresh_interval` fixes the problem.
